const DELETE_TODO = "DELETE_TODO";
const ADD_TODO = "ADD_TODO";
const EDIT_TODO = "EDIT_TODO";
const COMPLETE_TODO = "COMPLETE_TODO";
const COMPLETE_ALL = "COMPLETE_ALL";
const CLEAR_COMPLETED = "CLEAR_COMPLETED";

export {
  DELETE_TODO,
  ADD_TODO,
  EDIT_TODO,
  COMPLETE_TODO,
  COMPLETE_ALL,
  CLEAR_COMPLETED
};